title: James G. Saulsbury
email: jgsauls@ku.edu
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - projects.md
  - papers.md
  - cv.md

minima:

  # Generate social links in footer.
  #
  social_links:
     - { platform: twitter, name: Twitter, user_url: "https://twitter.com/jgsaulsbury" }
     - { platform: github, name: GitHub, user_url: "https://github.com/jgsaulsbury" }
     - { platform: researchgate, name: ResearchGate, user_url: "https://www.researchgate.net/profile/James-Saulsbury" }
     - { platform: google_scholar, name: Google Scholar, user_url: "https://scholar.google.com/citations?user=8_V5N1EAAAAJ" }
