title: James G. Saulsbury
email: j.g.saulsbury@nhm.uio.no
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - projects.md
  - papers.md
  - cv.md

minima:

  # Generate social links in footer.
  #
  social_links:
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=8_V5N1EAAAAJ" }
     - { platform: twitter,        user_url: "https://twitter.com/jgsaulsbury" }
     - { platform: github, user_url: "https://github.com/jgsaulsbury" }
     - { platform: researchgate,        user_url: "https://www.researchgate.net/profile/James-Saulsbury" }

